name: rool_dice_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_launcher_icons: ^0.10.0
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "assets/images/logo.png"  # veya renk hex
  adaptive_icon_foreground: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/pastel/dice-1.png
  - assets/images/pastel/dice-2.png
  - assets/images/pastel/dice-3.png
  - assets/images/pastel/dice-4.png
  - assets/images/pastel/dice-5.png
  - assets/images/pastel/dice-6.png
  - assets/images/pastel/dice-7.png
  - assets/images/pastel/dice-8.png
  - assets/images/pastel/dice-9.png
  - assets/images/pastel/dice-10.png
  - assets/images/pastel/dice-11.png
  - assets/images/pastel/dice-12.png
  - assets/images/pastel/dice-13.png
  - assets/images/pastel/dice-14.png
  - assets/images/pastel/dice-15.png
  - assets/images/pastel/dice-16.png
  - assets/images/pastel/dice-17.png
  - assets/images/pastel/dice-18.png
  - assets/images/pastel/dice-19.png
  - assets/images/pastel/dice-20.png
  - assets/images/pastel/dice-21.png
  - assets/images/pastel/dice-22.png
  - assets/images/pastel/dice-23.png
  - assets/images/pastel/dice-24.png

  - assets/images/candy/dice-1.png
  - assets/images/candy/dice-2.png
  - assets/images/candy/dice-3.png
  - assets/images/candy/dice-4.png
  - assets/images/candy/dice-5.png
  - assets/images/candy/dice-6.png
  - assets/images/candy/dice-7.png
  - assets/images/candy/dice-8.png
  - assets/images/candy/dice-9.png
  - assets/images/candy/dice-10.png
  - assets/images/candy/dice-11.png
  - assets/images/candy/dice-12.png
  - assets/images/candy/dice-13.png
  - assets/images/candy/dice-14.png
  - assets/images/candy/dice-15.png
  - assets/images/candy/dice-16.png
  - assets/images/candy/dice-17.png
  - assets/images/candy/dice-18.png
  - assets/images/candy/dice-19.png
  - assets/images/candy/dice-20.png
  - assets/images/candy/dice-21.png
  - assets/images/candy/dice-22.png
  - assets/images/candy/dice-23.png
  - assets/images/candy/dice-24.png

  - assets/images/earth/dice-1.png
  - assets/images/earth/dice-2.png
  - assets/images/earth/dice-3.png
  - assets/images/earth/dice-4.png
  - assets/images/earth/dice-5.png
  - assets/images/earth/dice-6.png
  - assets/images/earth/dice-7.png
  - assets/images/earth/dice-8.png
  - assets/images/earth/dice-9.png
  - assets/images/earth/dice-10.png
  - assets/images/earth/dice-11.png
  - assets/images/earth/dice-12.png
  - assets/images/earth/dice-13.png
  - assets/images/earth/dice-14.png
  - assets/images/earth/dice-15.png
  - assets/images/earth/dice-16.png
  - assets/images/earth/dice-17.png
  - assets/images/earth/dice-18.png
  - assets/images/earth/dice-19.png
  - assets/images/earth/dice-20.png
  - assets/images/earth/dice-21.png
  - assets/images/earth/dice-22.png
  - assets/images/earth/dice-23.png
  - assets/images/earth/dice-24.png

  - assets/images/sky/dice-1.png
  - assets/images/sky/dice-2.png
  - assets/images/sky/dice-3.png
  - assets/images/sky/dice-4.png
  - assets/images/sky/dice-5.png
  - assets/images/sky/dice-6.png
  - assets/images/sky/dice-7.png
  - assets/images/sky/dice-8.png
  - assets/images/sky/dice-9.png
  - assets/images/sky/dice-10.png
  - assets/images/sky/dice-11.png
  - assets/images/sky/dice-12.png
  - assets/images/sky/dice-13.png
  - assets/images/sky/dice-14.png
  - assets/images/sky/dice-15.png
  - assets/images/sky/dice-16.png
  - assets/images/sky/dice-17.png
  - assets/images/sky/dice-18.png
  - assets/images/sky/dice-19.png
  - assets/images/sky/dice-20.png
  - assets/images/sky/dice-21.png
  - assets/images/sky/dice-22.png
  - assets/images/sky/dice-23.png
  - assets/images/sky/dice-24.png

  - assets/images/spring/dice-1.png
  - assets/images/spring/dice-2.png
  - assets/images/spring/dice-3.png
  - assets/images/spring/dice-4.png
  - assets/images/spring/dice-5.png
  - assets/images/spring/dice-6.png
  - assets/images/spring/dice-7.png
  - assets/images/spring/dice-8.png
  - assets/images/spring/dice-9.png
  - assets/images/spring/dice-10.png
  - assets/images/spring/dice-11.png
  - assets/images/spring/dice-12.png
  - assets/images/spring/dice-13.png
  - assets/images/spring/dice-14.png
  - assets/images/spring/dice-15.png
  - assets/images/spring/dice-16.png
  - assets/images/spring/dice-17.png
  - assets/images/spring/dice-18.png
  - assets/images/spring/dice-19.png
  - assets/images/spring/dice-20.png
  - assets/images/spring/dice-21.png
  - assets/images/spring/dice-22.png
  - assets/images/spring/dice-23.png
  - assets/images/spring/dice-24.png

  - assets/images/warm/dice-1.png
  - assets/images/warm/dice-2.png
  - assets/images/warm/dice-3.png
  - assets/images/warm/dice-4.png
  - assets/images/warm/dice-5.png
  - assets/images/warm/dice-6.png
  - assets/images/warm/dice-7.png
  - assets/images/warm/dice-8.png
  - assets/images/warm/dice-9.png
  - assets/images/warm/dice-10.png
  - assets/images/warm/dice-11.png
  - assets/images/warm/dice-12.png
  - assets/images/warm/dice-13.png
  - assets/images/warm/dice-14.png
  - assets/images/warm/dice-15.png
  - assets/images/warm/dice-16.png
  - assets/images/warm/dice-17.png
  - assets/images/warm/dice-18.png
  - assets/images/warm/dice-19.png
  - assets/images/warm/dice-20.png
  - assets/images/warm/dice-21.png
  - assets/images/warm/dice-22.png
  - assets/images/warm/dice-23.png
  - assets/images/warm/dice-24.png

  - assets/images/pastel_t.png
  - assets/images/earth_t.png
  - assets/images/candy_t.png
  - assets/images/sky_t.png
  - assets/images/spring_t.png
  - assets/images/warm_t.png
  - assets/images/homepage.png
  - assets/images/range.png
  - assets/images/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
